version: "2"

linters:
  enable:
    # Default
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    # Formatting (now in formatters section)
    - misspell
    # Security
    - gosec
    # Error handling
    - errorlint
    # Code quality
    - revive
    - gocritic
    - gocyclo
    - dupl
    - unconvert
    - unparam

  settings:
    gocyclo:
      min-complexity: 20

    dupl:
      threshold: 150

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - whyNoLint
        - hugeParam
        - ifElseChain
        - paramTypeCombine
        - sprintfQuotedString
        - rangeValCopy

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

    gosec:
      excludes:
        - G104
        - G204
        - G301  # Directory permissions 0755 is fine for .cvx dirs
        - G304
        - G306
        - G404

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gocritic
          - gocyclo
          - gosec
      - path: cmd/(init|list)\.go
        linters:
          - gocyclo
      - linters:
          - revive
        text: "stutters"
      - linters:
          - revive
        text: "AddProjectV2ItemById"
      - path: pkg/utils/
        linters:
          - revive
        text: "var-naming"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/xrsl/cvx
