# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-01-03T09:25:04+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel


class BodyParagraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paragraph: str


class BulletEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    bullet: str


class Content(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: list[BodyParagraph] | None = None
    closing: str
    opening: str
    salutation: str


class Date(RootModel[str | int | None]):
    root: str | int | None


class ExactDate(RootModel[str | int | Literal['present'] | None]):
    root: str | int | Literal['present'] | None


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: str | Literal['auto']
    position_applied: str | None = None


class OneLineEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    group: str
    items: str


class PublicationEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    authors: list[str] | None = None
    date: Date | None = None
    doi: str | None = None
    journal: str | None = None
    summary: str | None = None
    title: str
    url: str | None = None


class Recipient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    company: str
    name: str
    title: str | None = None


class Sender(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str | None = None
    email: str
    github: str | None = None
    linkedin: str | None = None
    name: str
    phone: str | None = None


class SocialNetwork(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    network: (
        Literal['LinkedIn']
        | Literal['GitHub']
        | Literal['GitLab']
        | Literal['Instagram']
        | Literal['Twitter']
        | Literal['X']
        | str
    )
    username: str


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    area: str | None = None
    company: str | None = None
    date: Date | None = None
    degree: str | None = None
    end_date: ExactDate | None = None
    highlights: list[str] | None = None
    institution: str | None = None
    location: str | None = None
    name: str | None = None
    position: str | None = None
    start_date: Date | None = None
    summary: str | None = None
    title: str | None = None


class Letter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: Content
    metadata: Metadata
    recipient: Recipient
    sender: Sender


class Sections(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    courses: list[Entry] | None = None
    education: list[Entry] | None = None
    experience: list[Entry] | None = None
    hobbies: list[BulletEntry] | None = None
    honors_and_awards: list[Entry] | None = None
    motivation: str | None = None
    publications: list[PublicationEntry] | None = None
    references: list[str] | None = None
    skills: list[OneLineEntry] | None = None
    summary: str | None = None
    values: list[BulletEntry] | None = None


class CV(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    email: str | list[str] | None = None
    expertise_tags: list[str] | None = None
    headline: str | None = None
    location: str | None = None
    name: str | None = None
    phone: str | list[str] | None = None
    sections: Sections | None = None
    socials: list[SocialNetwork] | None = None
    website: str | list[str] | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cv: CV | None = None
    letter: Letter | None = None
