# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-01-04T15:22:42+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel


class BodyParagraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paragraph: str


class Content(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: list[BodyParagraph] | None = None
    closing: str
    opening: str
    salutation: str


class Date(RootModel[str | int | None]):
    root: str | int | None


class ExactDate(RootModel[str | int | Literal['present'] | None]):
    root: str | int | Literal['present'] | None


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: str | Literal['auto']
    position_applied: str | None = None


class PublicationEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    authors: list[str] | None = None
    date: Date | None = None
    doi: str | None = None
    journal: str | None = None
    summary: str | None = None
    title: str
    url: str | None = None


class Recipient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    company: str
    name: str
    title: str | None = None


class Sender(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str | None = None
    email: str
    github: str | None = None
    linkedin: str | None = None
    name: str
    phone: str | None = None


class SkillEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    group: str
    items: str | list[str]


class SocialNetwork(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    network: (
        Literal['LinkedIn']
        | Literal['GitHub']
        | Literal['GitLab']
        | Literal['Instagram']
        | Literal['Twitter']
        | Literal['X']
        | str
    )
    username: str


class TextEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    area: str | None = None
    company: str | None = None
    date: Date | None = None
    degree: str | None = None
    end_date: ExactDate | None = None
    highlights: list[str] | None = None
    institution: str | None = None
    location: str | None = None
    name: str | None = None
    position: str | None = None
    start_date: Date | None = None
    summary: str | None = None
    title: str | None = None


class Letter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: Content
    metadata: Metadata
    recipient: Recipient
    sender: Sender


class CV(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str | None = None
    awards: list[Entry] | None = None
    courses: list[Entry] | None = None
    education: list[Entry] | None = None
    email: str | list[str] | None = None
    experience: list[Entry] | None = None
    headline: str | None = None
    hobbies: list[str] | None = None
    keywords: list[str] | None = None
    location: str | None = None
    motivation: TextEntry | None = None
    name: str | None = None
    phone: str | list[str] | None = None
    profiles: list[SocialNetwork] | None = None
    publications: list[PublicationEntry] | None = None
    references: str | list[str] | None = None
    skills: list[SkillEntry] | None = None
    summary: TextEntry | None = None
    values: list[str] | None = None
    website: str | list[str] | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cv: CV | None = None
    letter: Letter | None = None
